# Generated by Django 5.0.6 on 2024-07-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0002_fornecedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
    ]
